// <auto-generated />
using System;
using ASP.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230914092810_Attribute")]
    partial class Attribute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.DataLayer.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complexity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.HeroToUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("UserId");

                    b.ToTable("HeroToUsers");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.Power", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cooldown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeroId")
                        .HasColumnType("int");

                    b.Property<string>("PowerDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Powers");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Carry")
                        .HasColumnType("real");

                    b.Property<float>("Disabler")
                        .HasColumnType("real");

                    b.Property<float>("Durable")
                        .HasColumnType("real");

                    b.Property<float>("Escape")
                        .HasColumnType("real");

                    b.Property<int?>("HeroId")
                        .HasColumnType("int");

                    b.Property<float>("Initiator")
                        .HasColumnType("real");

                    b.Property<float>("Jungler")
                        .HasColumnType("real");

                    b.Property<float>("Nuker")
                        .HasColumnType("real");

                    b.Property<float>("Pusher")
                        .HasColumnType("real");

                    b.Property<float>("Support")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique()
                        .HasFilter("[HeroId] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Armor")
                        .HasColumnType("real");

                    b.Property<float>("Attack")
                        .HasColumnType("real");

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("real");

                    b.Property<int?>("HeroId")
                        .HasColumnType("int");

                    b.Property<float>("MagicResist")
                        .HasColumnType("real");

                    b.Property<float>("MoveSpoeed")
                        .HasColumnType("real");

                    b.Property<float>("Range")
                        .HasColumnType("real");

                    b.Property<float>("Visibility")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique()
                        .HasFilter("[HeroId] IS NOT NULL");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.HeroToUsers", b =>
                {
                    b.HasOne("ASP.DataLayer.Models.Hero", null)
                        .WithMany("HeroToUsers")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.DataLayer.Models.User", null)
                        .WithMany("HeroToUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASP.DataLayer.Models.Power", b =>
                {
                    b.HasOne("ASP.DataLayer.Models.Hero", null)
                        .WithMany("PowerList")
                        .HasForeignKey("HeroId");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.Roles", b =>
                {
                    b.HasOne("ASP.DataLayer.Models.Hero", "Hero")
                        .WithOne("Roles")
                        .HasForeignKey("ASP.DataLayer.Models.Roles", "HeroId");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.Stats", b =>
                {
                    b.HasOne("ASP.DataLayer.Models.Hero", "Hero")
                        .WithOne("Stats")
                        .HasForeignKey("ASP.DataLayer.Models.Stats", "HeroId");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.Hero", b =>
                {
                    b.Navigation("HeroToUsers");

                    b.Navigation("PowerList");

                    b.Navigation("Roles");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("ASP.DataLayer.Models.User", b =>
                {
                    b.Navigation("HeroToUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
